### ISSUE TITLE
Creating New Pokemon

### ISSUE THREAD

**Issue by Zeraanan** [Corvimae/pokemon-manager-2#1]
>Go to "Unassigned Pokemon" and create a new Mon
>Put in Values for all of the stats
>Notice how HP, and all Evasions are not calculated correctly
>Finish making Mon and then drag them to your Trainer to make them Active
>The Values are now correct 
HMMMMMMMMMMMMMMMMMMM

**Comment by Corvimae** [comment]
Those formulas are determined by the campaign GM, and so they will change depending on the campaign that the trainer is assigned to.
